// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
using System;
using System.Numerics;
using System.Runtime.CompilerServices;

namespace SecureValue.Numerics
{
	public partial struct SecurePlane : IEquatable<Plane>, IEquatable<SecurePlane>
	{
		/// <summary>Tests a secured Plane value and a plain Plane value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecurePlane a, Plane b) =>
			a.Decrypted == b;

		/// <summary>Tests a plain Plane value and a secured Plane value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(Plane a, SecurePlane b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured Plane value and a plain Plane value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecurePlane a, Plane b) =>
			a.Decrypted != b;

		/// <summary>Tests a plain Plane value and a secured Plane value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(Plane a, SecurePlane b) =>
			a != b.Decrypted;

		/// <summary>Compares the decrypted value with a plain Plane value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<Plane>.Equals(Plane other) =>
			Decrypted.Equals(other);
	}
}
