// Deterministic file emission: LF, no BOM, tab indentation.
// Files are only rewritten when content changes.
namespace SecureValue.CodeGen;

using System.Text;

internal static class GenWriter
{
	/// <summary>Emits one generated partial wrapper file. Returns true when written.</summary>
	public static bool WriteWrapper(
		string repoRoot,
		WrapperSpec spec,
		string members,
		bool checkOnly,
		ref int changed
	)
	{
		string body = BuildFile(
			spec,
			members,
			Interfaces.InterfacesFor(spec),
			Interfaces.WantsSpanFormat(spec) ? Interfaces.SpanFormatGuard(spec) : null,
			Interfaces.ParsableFor(spec),
			Interfaces.Utf8For(spec),
			Interfaces.WantsConditionalFormattable(spec),
			GuardFor(spec),
			UsingsFor(spec)
		);
		string path = Path.Combine(
			repoRoot,
			"SecureValue",
			spec.RelativeDir,
			spec.GeneratedFileName
		);
		return WriteFile(path, body, checkOnly, ref changed);
	}

	/// <summary>Whole-content preprocessor guard (TFM-gated wrappers).</summary>
	internal static string? GuardFor(WrapperSpec spec) =>
		spec.SecureName switch
		{
			"SecureRune" => "NET",
			"SecureDateOnly" or "SecureTimeOnly" => "NET6_0_OR_GREATER",
			_ => spec.Namespace == "SecureValue.Unity" ? "UNITY_5_3_OR_NEWER" : null,
		};

	/// <summary>Extra usings beyond System + Runtime.CompilerServices.</summary>
	internal static string[] UsingsFor(WrapperSpec spec)
	{
		if (spec.Namespace == "SecureValue.Unity")
		{
			return new[] { "using UnityEngine;" };
		}

		return spec.SecureName switch
		{
			"SecureRune" => new[] { "using System.Text;" },
			"SecureString" => new[] { "using System.Collections.Generic;" },
			_ => spec.RelativeDir.EndsWith("Numerics", StringComparison.Ordinal)
				? new[] { "using System.Numerics;" }
				: Array.Empty<string>(),
		};
	}

	internal static string BuildFile(
		WrapperSpec spec,
		string members,
		string[] interfaces,
		string? spanFormatGuard,
		string[] parsable,
		string[] utf8,
		bool conditionalFormattable,
		string? guard,
		string[] extraUsings
	)
	{
		StringBuilder sb = new();
		// NOTE: no '#nullable enable' here by design. Generated partials are
		// nullable-oblivious (and emit no '?' annotations): with the library
		// csproj on <Nullable>disable</Nullable>, annotations would raise
		// CS8632, while oblivious signatures keep null literals warning-free
		// for consumers (including Unity, which compiles sources without the
		// csproj). Hand-written partials keep their own '#nullable enable'.
		sb.Append("// <auto-generated>\n");
		sb.Append("// This file was generated by SecureValue.CodeGen. Do not edit by hand;\n");
		sb.Append("// edit the generator and re-run: dotnet run --project SecureValue.CodeGen\n");
		sb.Append("// </auto-generated>\n");
		if (guard is not null && spec.Namespace == "SecureValue.Unity")
		{
			sb.Append($"#if {guard}\n");
		}

		sb.Append("using System;\n");
		foreach (string u in extraUsings)
		{
			sb.Append(u + "\n");
		}

		sb.Append("using System.Runtime.CompilerServices;\n");
		sb.Append('\n');
		sb.Append($"namespace {spec.Namespace}\n");
		sb.Append("{\n");
		if (guard is not null && spec.Namespace != "SecureValue.Unity")
		{
			sb.Append($"#if {guard}\n");
		}

		sb.Append($"\tpublic partial struct {spec.SecureName}");
		if (interfaces.Length != 0)
		{
			sb.Append(" : " + string.Join(", ", interfaces));
		}

		if (spanFormatGuard is not null)
		{
			sb.Append($"\n#if {spanFormatGuard}\n\t\t\t,\n\t\t\tISpanFormattable\n#endif");
		}

		if (conditionalFormattable)
		{
			sb.Append("\n#if NET7_0_OR_GREATER\n\t\t\t,\n\t\t\tIFormattable\n#endif");
		}

		if (parsable.Length != 0)
		{
			sb.Append(
				"\n#if NET7_0_OR_GREATER\n\t\t\t,\n\t\t\t"
					+ string.Join(",\n\t\t\t", parsable)
					+ "\n#endif"
			);
		}

		if (utf8.Length != 0)
		{
			sb.Append(
				"\n#if NET8_0_OR_GREATER\n\t\t\t,\n\t\t\t"
					+ string.Join(",\n\t\t\t", utf8)
					+ "\n#endif"
			);
		}

		sb.Append("\n\t{\n");
		sb.Append(SeparateMembers(members));
		sb.Append("\t}\n");
		if (guard is not null && spec.Namespace != "SecureValue.Unity")
		{
			sb.Append($"#endif\n");
		}

		sb.Append("}\n");
		if (guard is not null && spec.Namespace == "SecureValue.Unity")
		{
			sb.Append($"#endif\n");
		}

		return sb.ToString();
	}

	/// <summary>Blank-line separators between members (repo convention).</summary>
	internal static string SeparateMembers(string members) =>
		members
			.Replace(";\n\t\t/// <summary>", ";\n\n\t\t/// <summary>", StringComparison.Ordinal)
			.Replace("}\n\t\t/// <summary>", "}\n\n\t\t/// <summary>", StringComparison.Ordinal);

	/// <summary>Writes <paramref name="path"/> when content differs. LF, no BOM.</summary>
	public static bool WriteFile(string path, string content, bool checkOnly, ref int changed)
	{
		string? existing = File.Exists(path) ? File.ReadAllText(path) : null;
		if (existing == content)
		{
			return false;
		}

		changed++;
		if (!checkOnly)
		{
			File.WriteAllText(
				path,
				content,
				new UTF8Encoding(encoderShouldEmitUTF8Identifier: false)
			);
		}

		return true;
	}
}
