// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
#if UNITY_5_3_OR_NEWER
using System;
using UnityEngine;
using System.Runtime.CompilerServices;

namespace SecureValue.Unity
{
	public partial struct SecureRect : IEquatable<Rect>, IEquatable<SecureRect>, ISecureValue<Rect>
	{
		/// <summary>Tests a secured Rect value and a plain Rect value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureRect a, Rect b) =>
			a.Decrypted == b;

		/// <summary>Tests a plain Rect value and a secured Rect value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(Rect a, SecureRect b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured Rect value and a plain Rect value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureRect a, Rect b) =>
			a.Decrypted != b;

		/// <summary>Tests a plain Rect value and a secured Rect value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(Rect a, SecureRect b) =>
			a != b.Decrypted;

		/// <summary>Compares the decrypted value with a plain Rect value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<Rect>.Equals(Rect other) =>
			Decrypted.Equals(other);
	}
}
#endif
