// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
#if UNITY_5_3_OR_NEWER
using System;
using UnityEngine;
using System.Runtime.CompilerServices;

namespace SecureValue.Unity
{
	public partial struct SecureVector4 : IEquatable<SecureVector4>, IEquatable<Vector4>, IFormattable
	{
		/// <summary>Tests a secured Vector4 value and a plain Vector4 value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureVector4 a, Vector4 b) =>
			a.Decrypted == b;

		/// <summary>Tests a plain Vector4 value and a secured Vector4 value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(Vector4 a, SecureVector4 b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured Vector4 value and a plain Vector4 value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureVector4 a, Vector4 b) =>
			a.Decrypted != b;

		/// <summary>Tests a plain Vector4 value and a secured Vector4 value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(Vector4 a, SecureVector4 b) =>
			a != b.Decrypted;

		/// <summary>Adds a secured Vector4 value and a plain Vector4 value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector4 operator +(SecureVector4 a, Vector4 b) =>
			new SecureVector4(a.Decrypted + b);

		/// <summary>Adds a plain Vector4 value and a secured Vector4 value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector4 operator +(Vector4 a, SecureVector4 b) =>
			new SecureVector4(a + b.Decrypted);

		/// <summary>Subtracts a secured Vector4 value and a plain Vector4 value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector4 operator -(SecureVector4 a, Vector4 b) =>
			new SecureVector4(a.Decrypted - b);

		/// <summary>Subtracts a plain Vector4 value and a secured Vector4 value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector4 operator -(Vector4 a, SecureVector4 b) =>
			new SecureVector4(a - b.Decrypted);

		/// <summary>Multiplies a secured Vector4 value by a plain float factor.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector4 operator *(SecureVector4 a, float b) =>
			new SecureVector4(a.Decrypted * b);

		/// <summary>Divides a secured Vector4 value by a plain float factor.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector4 operator /(SecureVector4 a, float b) =>
			new SecureVector4(a.Decrypted / b);

		/// <summary>Compares the decrypted value with a plain Vector4 value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<Vector4>.Equals(Vector4 other) =>
			Decrypted.Equals(other);
	}
}
#endif
