// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
#if UNITY_5_3_OR_NEWER
using System;
using UnityEngine;
using System.Runtime.CompilerServices;

namespace SecureValue.Unity
{
	public partial struct SecureColor : IEquatable<Color>, IEquatable<SecureColor>
	{
		/// <summary>Tests a secured Color value and a plain Color value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureColor a, Color b) =>
			a.Decrypted == b;

		/// <summary>Tests a plain Color value and a secured Color value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(Color a, SecureColor b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured Color value and a plain Color value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureColor a, Color b) =>
			a.Decrypted != b;

		/// <summary>Tests a plain Color value and a secured Color value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(Color a, SecureColor b) =>
			a != b.Decrypted;

		/// <summary>Adds a secured Color value and a plain Color value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureColor operator +(SecureColor a, Color b) =>
			new SecureColor(a.Decrypted + b);

		/// <summary>Adds a plain Color value and a secured Color value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureColor operator +(Color a, SecureColor b) =>
			new SecureColor(a + b.Decrypted);

		/// <summary>Subtracts a secured Color value and a plain Color value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureColor operator -(SecureColor a, Color b) =>
			new SecureColor(a.Decrypted - b);

		/// <summary>Subtracts a plain Color value and a secured Color value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureColor operator -(Color a, SecureColor b) =>
			new SecureColor(a - b.Decrypted);

		/// <summary>Multiplies a secured Color value by a plain float factor.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureColor operator *(SecureColor a, float b) =>
			new SecureColor(a.Decrypted * b);

		/// <summary>Compares the decrypted value with a plain Color value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<Color>.Equals(Color other) =>
			Decrypted.Equals(other);
	}
}
#endif
