// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
#if UNITY_5_3_OR_NEWER
using System;
using UnityEngine;
using System.Runtime.CompilerServices;

namespace SecureValue.Unity
{
	public partial struct SecureLayerMask : IEquatable<LayerMask>, IEquatable<SecureLayerMask>
	{
		/// <summary>Tests a secured LayerMask value and a plain LayerMask value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureLayerMask a, LayerMask b) =>
			a.Decrypted == b;

		/// <summary>Tests a plain LayerMask value and a secured LayerMask value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(LayerMask a, SecureLayerMask b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured LayerMask value and a plain LayerMask value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureLayerMask a, LayerMask b) =>
			a.Decrypted != b;

		/// <summary>Tests a plain LayerMask value and a secured LayerMask value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(LayerMask a, SecureLayerMask b) =>
			a != b.Decrypted;

		/// <summary>Compares the decrypted value with a plain LayerMask value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<LayerMask>.Equals(LayerMask other) =>
			Decrypted.Equals(other);
	}
}
#endif
