// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
#if UNITY_5_3_OR_NEWER
using System;
using UnityEngine;
using System.Runtime.CompilerServices;

namespace SecureValue.Unity
{
	public partial struct SecureMatrix4x4 : IEquatable<Matrix4x4>, IEquatable<SecureMatrix4x4>, ISecureValue<Matrix4x4>
	{
		/// <summary>Tests a secured Matrix4x4 value and a plain Matrix4x4 value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureMatrix4x4 a, Matrix4x4 b) =>
			a.Decrypted == b;

		/// <summary>Tests a plain Matrix4x4 value and a secured Matrix4x4 value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(Matrix4x4 a, SecureMatrix4x4 b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured Matrix4x4 value and a plain Matrix4x4 value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureMatrix4x4 a, Matrix4x4 b) =>
			a.Decrypted != b;

		/// <summary>Tests a plain Matrix4x4 value and a secured Matrix4x4 value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(Matrix4x4 a, SecureMatrix4x4 b) =>
			a != b.Decrypted;

		/// <summary>Multiplies a secured Matrix4x4 value and a plain Matrix4x4 value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureMatrix4x4 operator *(SecureMatrix4x4 a, Matrix4x4 b) =>
			new SecureMatrix4x4(a.Decrypted * b);

		/// <summary>Multiplies a plain Matrix4x4 value and a secured Matrix4x4 value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureMatrix4x4 operator *(Matrix4x4 a, SecureMatrix4x4 b) =>
			new SecureMatrix4x4(a * b.Decrypted);

		/// <summary>Compares the decrypted value with a plain Matrix4x4 value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<Matrix4x4>.Equals(Matrix4x4 other) =>
			Decrypted.Equals(other);
	}
}
#endif
