// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
#if UNITY_5_3_OR_NEWER
using System;
using UnityEngine;
using System.Runtime.CompilerServices;

namespace SecureValue.Unity
{
	public partial struct SecureRectInt : IEquatable<RectInt>, IEquatable<SecureRectInt>
	{
		/// <summary>Tests a secured RectInt value and a plain RectInt value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureRectInt a, RectInt b) =>
			a.Decrypted == b;

		/// <summary>Tests a plain RectInt value and a secured RectInt value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(RectInt a, SecureRectInt b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured RectInt value and a plain RectInt value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureRectInt a, RectInt b) =>
			a.Decrypted != b;

		/// <summary>Tests a plain RectInt value and a secured RectInt value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(RectInt a, SecureRectInt b) =>
			a != b.Decrypted;

		/// <summary>Compares the decrypted value with a plain RectInt value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<RectInt>.Equals(RectInt other) =>
			Decrypted.Equals(other);
	}
}
#endif
