// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
#if UNITY_5_3_OR_NEWER
using System;
using UnityEngine;
using System.Runtime.CompilerServices;

namespace SecureValue.Unity
{
	public partial struct SecureVector2Int : IEquatable<SecureVector2Int>, IEquatable<Vector2Int>
	{
		/// <summary>Tests a secured Vector2Int value and a plain Vector2Int value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureVector2Int a, Vector2Int b) =>
			a.Decrypted == b;

		/// <summary>Tests a plain Vector2Int value and a secured Vector2Int value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(Vector2Int a, SecureVector2Int b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured Vector2Int value and a plain Vector2Int value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureVector2Int a, Vector2Int b) =>
			a.Decrypted != b;

		/// <summary>Tests a plain Vector2Int value and a secured Vector2Int value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(Vector2Int a, SecureVector2Int b) =>
			a != b.Decrypted;

		/// <summary>Adds a secured Vector2Int value and a plain Vector2Int value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector2Int operator +(SecureVector2Int a, Vector2Int b) =>
			new SecureVector2Int(a.Decrypted + b);

		/// <summary>Adds a plain Vector2Int value and a secured Vector2Int value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector2Int operator +(Vector2Int a, SecureVector2Int b) =>
			new SecureVector2Int(a + b.Decrypted);

		/// <summary>Subtracts a secured Vector2Int value and a plain Vector2Int value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector2Int operator -(SecureVector2Int a, Vector2Int b) =>
			new SecureVector2Int(a.Decrypted - b);

		/// <summary>Subtracts a plain Vector2Int value and a secured Vector2Int value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector2Int operator -(Vector2Int a, SecureVector2Int b) =>
			new SecureVector2Int(a - b.Decrypted);

		/// <summary>Multiplies a secured Vector2Int value by a plain int factor.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector2Int operator *(SecureVector2Int a, int b) =>
			new SecureVector2Int(a.Decrypted * b);

		/// <summary>Divides a secured Vector2Int value by a plain int factor.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureVector2Int operator /(SecureVector2Int a, int b) =>
			new SecureVector2Int(a.Decrypted / b);

		/// <summary>Compares the decrypted value with a plain Vector2Int value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<Vector2Int>.Equals(Vector2Int other) =>
			Decrypted.Equals(other);
	}
}
#endif
