// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
#if UNITY_5_3_OR_NEWER
using System;
using UnityEngine;
using System.Runtime.CompilerServices;

namespace SecureValue.Unity
{
	public partial struct SecureBounds : IEquatable<Bounds>, IEquatable<SecureBounds>, ISecureValue<Bounds>
	{
		/// <summary>Tests a secured Bounds value and a plain Bounds value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureBounds a, Bounds b) =>
			a.Decrypted == b;

		/// <summary>Tests a plain Bounds value and a secured Bounds value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(Bounds a, SecureBounds b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured Bounds value and a plain Bounds value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureBounds a, Bounds b) =>
			a.Decrypted != b;

		/// <summary>Tests a plain Bounds value and a secured Bounds value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(Bounds a, SecureBounds b) =>
			a != b.Decrypted;

		/// <summary>Compares the decrypted value with a plain Bounds value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<Bounds>.Equals(Bounds other) =>
			Decrypted.Equals(other);
	}
}
#endif
