#nullable enable

//:property TargetFramework=net10.0
// Stages the Unity package Runtime sources:
// copies the single SecureValue project sources into
// SecureValue.Unity/Runtime/Generated/ so the package folder is self-contained.
// Also copies the root README.md over SecureValue.Unity/README.md verbatim
// (the root README is the single source of truth).
// CI can then feed this folder to Unity's -batchmode exporter to produce a .unitypackage.
//
// Layout mapping (kept stable so Unity .meta files survive):
//   SecureValue/Internal/* + SecureValue/Utility/* + SecureValue/Wrappers/Core/*
//     -> Runtime/Generated/Core/
//   SecureValue/Wrappers/Numerics -> Runtime/Generated/Numerics/
//   SecureValue/Wrappers/Unity/*    -> Runtime/Generated/Unity/
//
// Unity .meta automation (no manual Unity round-trip, no registry file):
// the committed .meta files ARE the registry. Staging never wipes directories,
// and a full-tree sync covers the ENTIRE SecureValue.Unity package (not just
// Generated/): every file gets a Unity-canonical .meta with the per-extension
// importer schema (.cs -> MonoImporter, .asmdef -> AssemblyDefinitionImporter,
// package .json -> PackageManifestImporter, everything else -> DefaultImporter;
// folders -> folderAsset + DefaultImporter). Missing metas are created with a
// fresh guid; guid-only (minimal) metas are upgraded to the canonical schema
// IN PLACE keeping their guid (Unity would rewrite them on import anyway, which
// is what dirties working copies); canonical metas are never rewritten, so
// guids — and Unity's references to them — stay stable. Orphan metas (no owner
// file/folder left) are deleted. Renames: `git mv` the file WITH its .meta to
// keep the guid.
//
// Run: dotnet run Tools/build-unity-package.cs   (from anywhere in the repo)

using System.Text;
using System.Text.RegularExpressions;

string repoRoot = FindRepoRoot(Environment.CurrentDirectory);
string pkg = Path.Combine(repoRoot, "SecureValue");
string unityPkg = Path.Combine(repoRoot, "SecureValue.Unity");
string outDir = Path.Combine(unityPkg, "Runtime", "Generated");

// Sync, never wipe: the on-disk .metas are the guid registry and must survive staging.
// Create separate directories per wrapper family.
string outDirCore = Path.Combine(outDir, "Core");
string outDirNumerics = Path.Combine(outDir, "Numerics");
string outDirUnity = Path.Combine(outDir, "Unity");

Directory.CreateDirectory(outDirCore);
Directory.CreateDirectory(outDirNumerics);
Directory.CreateDirectory(outDirUnity);

const string Header = """
//------------------------------------------------------------------------------
// <auto-generated>
// Generated by Tools/build-unity-package.cs - DO NOT EDIT.
// </auto-generated>
//------------------------------------------------------------------------------

""";

// UTF-8 with BOM, matching the previous PowerShell Set-Content -Encoding UTF8 output.
UTF8Encoding utf8WithBom = new(encoderShouldEmitUTF8Identifier: true);

HashSet<string> stagedCore = StageDir(Path.Combine(pkg, "Internal"), outDirCore, "core");
stagedCore.UnionWith(StageDir(Path.Combine(pkg, "Utility"), outDirCore, "core"));
stagedCore.UnionWith(StageDir(Path.Combine(pkg, "Wrappers", "Core"), outDirCore, "core"));
HashSet<string> stagedNumerics = StageDir(
	Path.Combine(pkg, "Wrappers", "Numerics"),
	outDirNumerics,
	"numerics"
);
HashSet<string> stagedUnity = StageDir(
	Path.Combine(pkg, "Wrappers", "Unity"),
	outDirUnity,
	"unity"
);

// Copy Unity-specific runtime sources (kept outside Generated so they can be edited directly).
HashSet<string> stagedRoot = new(StringComparer.Ordinal);
foreach (string file in Directory.EnumerateFiles(Path.Combine(unityPkg, "Runtime"), "*.cs"))
{
	string name = Path.GetFileName(file);
	File.Copy(file, Path.Combine(outDir, name), overwrite: true);
	stagedRoot.Add(name);

	Console.WriteLine($"staged {name} (unity)");
}

// Drop stale Generated outputs, then sync .metas across the whole Unity package.
CleanStale(outDirCore, stagedCore);
CleanStale(outDirNumerics, stagedNumerics);
CleanStale(outDirUnity, stagedUnity);
CleanStale(outDir, stagedRoot);

SyncMetaTree(unityPkg);

Console.WriteLine($"Runtime sources staged to {outDir}");

// Single-source the Unity readme: verbatim copy of the root README.md.
string unityReadme = Path.Combine(unityPkg, "README.md");
File.Copy(Path.Combine(repoRoot, "README.md"), unityReadme, overwrite: true);
Console.WriteLine("staged README.md (unity readme, verbatim from root)");

return;

HashSet<string> StageDir(string srcDir, string destDir, string label)
{
	HashSet<string> staged = new(StringComparer.Ordinal);
	if (!Directory.Exists(srcDir))
	{
		return staged;
	}
	var files = Directory
		.EnumerateFiles(srcDir, "*.cs", SearchOption.TopDirectoryOnly)
		.OrderBy(p => Path.GetFileName(p), StringComparer.Ordinal);

	foreach (string file in files)
	{
		string name = Path.GetFileName(file);
		string dest = Path.Combine(destDir, name);
		File.WriteAllText(dest, Header + File.ReadAllText(file), utf8WithBom);
		staged.Add(name);
		Console.WriteLine($"staged {name} ({label})");
	}

	return staged;
}

// Deletes staged outputs whose source file is gone (plus their .metas) and any
// orphan .cs.meta whose .cs is not staged. Other .metas (folder metas, etc.)
// are never touched.
void CleanStale(string destDir, HashSet<string> staged)
{
	foreach (
		string file in Directory.EnumerateFiles(destDir, "*.cs", SearchOption.TopDirectoryOnly)
	)
	{
		string name = Path.GetFileName(file);
		if (!staged.Contains(name))
		{
			File.Delete(file);
			string meta = file + ".meta";
			if (File.Exists(meta))
			{
				File.Delete(meta);
			}
			Console.WriteLine($"removed stale {name}");
		}
	}

	foreach (
		string meta in Directory.EnumerateFiles(destDir, "*.cs.meta", SearchOption.TopDirectoryOnly)
	)
	{
		string owner = Path.GetFileName(meta)[..^".meta".Length];
		if (!staged.Contains(owner))
		{
			File.Delete(meta);
			Console.WriteLine($"removed orphan {Path.GetFileName(meta)}");
		}
	}
}

// Walks the entire Unity package tree (the package root itself gets no .meta —
// that file would live at the repo root, outside the package): every folder
// gets a folder .meta, every non-.meta file gets a canonical per-extension
// .meta, orphan .metas are deleted. Existing canonical metas are never touched.
void SyncMetaTree(string root)
{
	IEnumerable<string> dirs = Directory
		.EnumerateDirectories(root, "*", SearchOption.AllDirectories)
		.OrderBy(d => d, StringComparer.Ordinal)
		.Prepend(root);

	foreach (string dir in dirs)
	{
		if (!dir.Equals(root, StringComparison.Ordinal))
		{
			EnsureFolderMeta(dir);
		}

		foreach (string file in Directory.EnumerateFiles(dir, "*", SearchOption.TopDirectoryOnly))
		{
			if (!file.EndsWith(".meta", StringComparison.OrdinalIgnoreCase))
			{
				EnsureFileMetaFor(file);
			}
		}

		foreach (
			string meta in Directory.EnumerateFiles(dir, "*.meta", SearchOption.TopDirectoryOnly)
		)
		{
			string owner = meta[..^".meta".Length];
			if (!File.Exists(owner) && !Directory.Exists(owner))
			{
				File.Delete(meta);
				Console.WriteLine($"removed orphan {RelativeToRoot(meta)}");
			}
		}
	}
}

// Creates the .meta for a file when missing; upgrades a guid-only (minimal)
// .meta to the canonical schema keeping its guid; leaves canonical metas
// byte-identical so guids never churn.
void EnsureFileMetaFor(string file)
{
	string meta = file + ".meta";
	if (!File.Exists(meta))
	{
		File.WriteAllText(meta, MetaTextFor(Path.GetExtension(file), Guid.NewGuid().ToString("N")));
		Console.WriteLine($"created meta for {RelativeToRoot(file)}");
		return;
	}

	string existing = File.ReadAllText(meta);
	if (!existing.Contains("Importer:", StringComparison.Ordinal))
	{
		// Tolerant on purpose: minimal metas in the wild vary in leading
		// whitespace and CRLF vs LF (git normalization, older templates).
		Match m = Regex.Match(
			existing,
			@"^\s*guid:\s*([0-9a-fA-F]{32})\r?$",
			RegexOptions.Multiline
		);
		if (m.Success)
		{
			string guid = m.Groups[1].Value.ToLowerInvariant();
			File.WriteAllText(meta, MetaTextFor(Path.GetExtension(file), guid));
			Console.WriteLine($"upgraded meta for {RelativeToRoot(file)}");
		}
	}
}

// Creates the folder .meta (e.g. Generated/Core.meta) when missing; existing
// ones are left byte-identical. Byte-identical to Unity's own folder metas.
void EnsureFolderMeta(string dir)
{
	string meta = dir + ".meta";
	if (File.Exists(meta))
	{
		return;
	}

	File.WriteAllText(meta, FolderMetaText(Guid.NewGuid().ToString("N")));
	Console.WriteLine($"created folder meta for {RelativeToRoot(dir)}");
}

string RelativeToRoot(string path) => Path.GetRelativePath(unityPkg, path);

// Unity-canonical .meta text per file extension (LF, no BOM, trailing newline),
// matching what Unity 2021.3 itself writes on import.
string MetaTextFor(string extension, string guid) =>
	extension.ToLowerInvariant() switch
	{
		".cs" => ScriptMetaText(guid),
		".asmdef" => PlainImporterMetaText(guid, "AssemblyDefinitionImporter"),
		".json" => PlainImporterMetaText(guid, "PackageManifestImporter"),
		_ => PlainImporterMetaText(guid, "DefaultImporter"),
	};

string ScriptMetaText(string guid) =>
	"fileFormatVersion: 2\n"
	+ $"guid: {guid}\n"
	+ "MonoImporter:\n"
	+ "  externalObjects: {}\n"
	+ "  serializedVersion: 2\n"
	+ "  defaultReferences: []\n"
	+ "  executionOrder: 0\n"
	+ "  icon: {instanceID: 0}\n"
	+ "  userData: \n"
	+ "  assetBundleName: \n"
	+ "  assetBundleVariant: \n";

string PlainImporterMetaText(string guid, string importer) =>
	"fileFormatVersion: 2\n"
	+ $"guid: {guid}\n"
	+ $"{importer}:\n"
	+ "  externalObjects: {}\n"
	+ "  userData: \n"
	+ "  assetBundleName: \n"
	+ "  assetBundleVariant: \n";

string FolderMetaText(string guid) =>
	"fileFormatVersion: 2\n"
	+ $"guid: {guid}\n"
	+ "folderAsset: yes\n"
	+ "DefaultImporter:\n"
	+ "  externalObjects: {}\n"
	+ "  userData: \n"
	+ "  assetBundleName: \n"
	+ "  assetBundleVariant: \n";

static string FindRepoRoot(string start)
{
	string? dir = start;

	while (dir is not null)
	{
		if (File.Exists(Path.Combine(dir, "SecureValue.slnx")))
		{
			return dir;
		}

		dir = Path.GetDirectoryName(dir);
	}

	throw new InvalidOperationException(
		$"Could not locate SecureValue.slnx upward from '{start}'. Run from inside the repo."
	);
}
