// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
using System;
using System.Text;
using System.Runtime.CompilerServices;

namespace SecureValue
{
#if NET
	public partial struct SecureRune : IComparable, IComparable<Rune>, IComparable<SecureRune>, IEquatable<Rune>, IEquatable<SecureRune>
#if NET7_0_OR_GREATER
			,
			ISpanFormattable
#endif
#if NET7_0_OR_GREATER
			,
			IFormattable
#endif
#if NET8_0_OR_GREATER
			,
			IUtf8SpanFormattable,
			IUtf8SpanParsable<SecureRune>
#endif
	{
		/// <summary>Tests a secured Rune value and a Rune value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureRune a, Rune b) =>
			a.Decrypted == b;

		/// <summary>Tests a Rune value and a secured Rune value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(Rune a, SecureRune b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured Rune value and a Rune value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureRune a, Rune b) =>
			a.Decrypted != b;

		/// <summary>Tests a Rune value and a secured Rune value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(Rune a, SecureRune b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured Rune value and a Rune value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureRune a, Rune b) =>
			a.Decrypted < b;

		/// <summary>Compares a Rune value and a secured Rune value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(Rune a, SecureRune b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured Rune value and a Rune value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureRune a, Rune b) =>
			a.Decrypted <= b;

		/// <summary>Compares a Rune value and a secured Rune value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(Rune a, SecureRune b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured Rune value and a Rune value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureRune a, Rune b) =>
			a.Decrypted > b;

		/// <summary>Compares a Rune value and a secured Rune value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(Rune a, SecureRune b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured Rune value and a Rune value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureRune a, Rune b) =>
			a.Decrypted >= b;

		/// <summary>Compares a Rune value and a secured Rune value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(Rune a, SecureRune b) =>
			a >= b.Decrypted;

		/// <summary>Compares the decrypted value with a plain Rune value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<Rune>.Equals(Rune other) =>
			Decrypted.Equals(other);

		/// <summary>Compares the decrypted value with a plain Rune value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IComparable<Rune>.CompareTo(Rune other) =>
			Decrypted.CompareTo(other);
#if NET7_0_OR_GREATER
		/// <summary>Tries to format the decrypted value into the destination span.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			((System.ISpanFormattable)Decrypted).TryFormat(destination, out charsWritten, format, provider);
#endif
#if NET8_0_OR_GREATER
		/// <summary>Parses UTF-8 bytes holding exactly one rune into its secured form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureRune System.IUtf8SpanParsable<SecureRune>.Parse(ReadOnlySpan<byte> s, IFormatProvider provider)
		{
			if (System.Text.Rune.DecodeFromUtf8(s, out System.Text.Rune rune, out int consumed) == System.Buffers.OperationStatus.Done && consumed == s.Length)
			{
				return new SecureRune(rune);
			}

			throw new System.FormatException("The UTF-8 input does not contain exactly one encoded rune.");
		}

		/// <summary>Tries to parse UTF-8 bytes holding exactly one rune into its secured form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IUtf8SpanParsable<SecureRune>.TryParse(ReadOnlySpan<byte> s, IFormatProvider provider, out SecureRune result)
		{
			if (System.Text.Rune.DecodeFromUtf8(s, out System.Text.Rune rune, out int consumed) == System.Buffers.OperationStatus.Done && consumed == s.Length)
			{
				result = new SecureRune(rune);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Tries to format the decrypted value as UTF-8 bytes.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			((System.IUtf8SpanFormattable)Decrypted).TryFormat(utf8Destination, out bytesWritten, format, provider);
#endif
	}
#endif
}
