// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
using System;
using System.Runtime.CompilerServices;

namespace SecureValue
{
	public partial struct SecureGuid : IComparable, IComparable<Guid>, IComparable<SecureGuid>, IEquatable<Guid>, IEquatable<SecureGuid>, IFormattable, ISecureValue<Guid>
#if NET6_0_OR_GREATER
			,
			ISpanFormattable
#endif
#if NET7_0_OR_GREATER
			,
			IParsable<SecureGuid>,
			ISpanParsable<SecureGuid>
#endif
#if NET8_0_OR_GREATER
			,
			IUtf8SpanFormattable,
			IUtf8SpanParsable<SecureGuid>
#endif
	{
		/// <summary>Tests a secured Guid value and a Guid value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureGuid a, Guid b) =>
			a.Decrypted == b;

		/// <summary>Tests a Guid value and a secured Guid value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(Guid a, SecureGuid b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured Guid value and a Guid value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureGuid a, Guid b) =>
			a.Decrypted != b;

		/// <summary>Tests a Guid value and a secured Guid value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(Guid a, SecureGuid b) =>
			a != b.Decrypted;

		/// <summary>Compares the decrypted value with a plain Guid value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<Guid>.Equals(Guid other) =>
			Decrypted.Equals(other);

		/// <summary>Compares the decrypted value with a plain Guid value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IComparable<Guid>.CompareTo(Guid other) =>
			Decrypted.CompareTo(other);
#if NET6_0_OR_GREATER
		/// <summary>Tries to format the decrypted value into the destination span.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			Decrypted.TryFormat(destination, out charsWritten, format);
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureGuid parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureGuid System.IParsable<SecureGuid>.Parse(string s, IFormatProvider provider) =>
			new SecureGuid(Guid.Parse(s, provider));

		/// <summary>Tries to parse input into its secured form (explicit SecureGuid parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IParsable<SecureGuid>.TryParse(string s, IFormatProvider provider, out SecureGuid result)
		{
			if (Guid.TryParse(s, provider, out Guid plain))
			{
				result = new SecureGuid(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureGuid parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureGuid System.ISpanParsable<SecureGuid>.Parse(ReadOnlySpan<char> s, IFormatProvider provider)
		{
			if (Guid.TryParse(s, provider, out Guid plain))
			{
				return new SecureGuid(plain);
			}

			throw new System.FormatException("Input was not in a correct format.");
		}

		/// <summary>Tries to parse input into its secured form (explicit SecureGuid parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.ISpanParsable<SecureGuid>.TryParse(ReadOnlySpan<char> s, IFormatProvider provider, out SecureGuid result)
		{
			if (Guid.TryParse(s, provider, out Guid plain))
			{
				result = new SecureGuid(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureGuid parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureGuid System.IUtf8SpanParsable<SecureGuid>.Parse(ReadOnlySpan<byte> s, IFormatProvider provider) =>
			new SecureGuid(Guid.Parse(System.Text.Encoding.UTF8.GetString(s), provider));

		/// <summary>Tries to parse input into its secured form (explicit SecureGuid parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IUtf8SpanParsable<SecureGuid>.TryParse(ReadOnlySpan<byte> s, IFormatProvider provider, out SecureGuid result)
		{
			if (Guid.TryParse(System.Text.Encoding.UTF8.GetString(s), provider, out Guid plain))
			{
				result = new SecureGuid(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Tries to format the decrypted value as UTF-8 bytes.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			((System.IUtf8SpanFormattable)Decrypted).TryFormat(utf8Destination, out bytesWritten, format, provider);
#endif
	}
}
