// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
using System;
using System.Runtime.CompilerServices;

namespace SecureValue
{
#if NET6_0_OR_GREATER
	public partial struct SecureDateOnly : IComparable, IComparable<DateOnly>, IComparable<SecureDateOnly>, IEquatable<DateOnly>, IEquatable<SecureDateOnly>, IFormattable
#if NET6_0_OR_GREATER
			,
			ISpanFormattable
#endif
#if NET7_0_OR_GREATER
			,
			IParsable<SecureDateOnly>,
			ISpanParsable<SecureDateOnly>
#endif
#if NET8_0_OR_GREATER
			,
			IUtf8SpanFormattable
#endif
	{
		/// <summary>Tests a secured DateOnly value and a DateOnly value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureDateOnly a, DateOnly b) =>
			a.Decrypted == b;

		/// <summary>Tests a DateOnly value and a secured DateOnly value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(DateOnly a, SecureDateOnly b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured DateOnly value and a DateOnly value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureDateOnly a, DateOnly b) =>
			a.Decrypted != b;

		/// <summary>Tests a DateOnly value and a secured DateOnly value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(DateOnly a, SecureDateOnly b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured DateOnly value and a DateOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureDateOnly a, DateOnly b) =>
			a.Decrypted < b;

		/// <summary>Compares a DateOnly value and a secured DateOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(DateOnly a, SecureDateOnly b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured DateOnly value and a DateOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureDateOnly a, DateOnly b) =>
			a.Decrypted <= b;

		/// <summary>Compares a DateOnly value and a secured DateOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(DateOnly a, SecureDateOnly b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured DateOnly value and a DateOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureDateOnly a, DateOnly b) =>
			a.Decrypted > b;

		/// <summary>Compares a DateOnly value and a secured DateOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(DateOnly a, SecureDateOnly b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured DateOnly value and a DateOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureDateOnly a, DateOnly b) =>
			a.Decrypted >= b;

		/// <summary>Compares a DateOnly value and a secured DateOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(DateOnly a, SecureDateOnly b) =>
			a >= b.Decrypted;

		/// <summary>Compares the decrypted value with a plain DateOnly value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<DateOnly>.Equals(DateOnly other) =>
			Decrypted.Equals(other);

		/// <summary>Compares the decrypted value with a plain DateOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IComparable<DateOnly>.CompareTo(DateOnly other) =>
			Decrypted.CompareTo(other);
#if NET6_0_OR_GREATER
		/// <summary>Tries to format the decrypted value into the destination span.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			Decrypted.TryFormat(destination, out charsWritten, format, provider);
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureDateOnly parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureDateOnly System.IParsable<SecureDateOnly>.Parse(string s, IFormatProvider provider) =>
			new SecureDateOnly(DateOnly.Parse(s, provider));

		/// <summary>Tries to parse input into its secured form (explicit SecureDateOnly parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IParsable<SecureDateOnly>.TryParse(string s, IFormatProvider provider, out SecureDateOnly result)
		{
			if (DateOnly.TryParse(s, provider, System.Globalization.DateTimeStyles.None, out DateOnly plain))
			{
				result = new SecureDateOnly(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureDateOnly parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureDateOnly System.ISpanParsable<SecureDateOnly>.Parse(ReadOnlySpan<char> s, IFormatProvider provider)
		{
			if (DateOnly.TryParse(s, provider, System.Globalization.DateTimeStyles.None, out DateOnly plain))
			{
				return new SecureDateOnly(plain);
			}

			throw new System.FormatException("Input was not in a correct format.");
		}

		/// <summary>Tries to parse input into its secured form (explicit SecureDateOnly parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.ISpanParsable<SecureDateOnly>.TryParse(ReadOnlySpan<char> s, IFormatProvider provider, out SecureDateOnly result)
		{
			if (DateOnly.TryParse(s, provider, System.Globalization.DateTimeStyles.None, out DateOnly plain))
			{
				result = new SecureDateOnly(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Tries to format the decrypted value as UTF-8 bytes.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			((System.IUtf8SpanFormattable)Decrypted).TryFormat(utf8Destination, out bytesWritten, format, provider);
#endif
	}
#endif
}
