// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
using System;
using System.Runtime.CompilerServices;

namespace SecureValue
{
	public partial struct SecureByte : IComparable, IComparable<SecureByte>, IComparable<byte>, IConvertible, IEquatable<SecureByte>, IEquatable<byte>, IFormattable, ISecureValue<byte>
#if NET6_0_OR_GREATER
			,
			ISpanFormattable
#endif
#if NET7_0_OR_GREATER
			,
			IParsable<SecureByte>,
			ISpanParsable<SecureByte>
#endif
#if NET8_0_OR_GREATER
			,
			IUtf8SpanFormattable,
			IUtf8SpanParsable<SecureByte>
#endif
	{
		/// <summary>Tests two secured byte values for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureByte left, SecureByte right) =>
			left.Equals(right);

		/// <summary>Tests two secured byte values for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureByte left, SecureByte right) =>
			!left.Equals(right);

		/// <summary>Compares two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureByte left, SecureByte right) =>
			left.Decrypted < right.Decrypted;

		/// <summary>Compares two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureByte left, SecureByte right) =>
			left.Decrypted <= right.Decrypted;

		/// <summary>Compares two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureByte left, SecureByte right) =>
			left.Decrypted > right.Decrypted;

		/// <summary>Compares two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureByte left, SecureByte right) =>
			left.Decrypted >= right.Decrypted;

		/// <summary>Adds two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator +(SecureByte a, SecureByte b) =>
			new SecureByte((byte)(a.Decrypted + b.Decrypted));

		/// <summary>Subtracts two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator -(SecureByte a, SecureByte b) =>
			new SecureByte((byte)(a.Decrypted - b.Decrypted));

		/// <summary>Multiplies two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator *(SecureByte a, SecureByte b) =>
			new SecureByte((byte)(a.Decrypted * b.Decrypted));

		/// <summary>Divides two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator /(SecureByte a, SecureByte b) =>
			new SecureByte((byte)(a.Decrypted / b.Decrypted));

		/// <summary>Remainders two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator %(SecureByte a, SecureByte b) =>
			new SecureByte((byte)(a.Decrypted % b.Decrypted));

		/// <summary>Negates a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator -(SecureByte a) =>
			new SecureByte((byte)(-a.Decrypted));

		/// <summary>Applies unary plus to a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator +(SecureByte a) =>
			new SecureByte((byte)(+a.Decrypted));

		/// <summary>Increments a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator ++(SecureByte a) =>
			new SecureByte((byte)(a.Decrypted + 1));

		/// <summary>Decrements a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator --(SecureByte a) =>
			new SecureByte((byte)(a.Decrypted - 1));

		/// <summary>Computes the bitwise NOT of a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator ~(SecureByte a) =>
			new SecureByte((byte)(~a.Decrypted));

		/// <summary>Computes the bitwise AND of two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator &(SecureByte a, SecureByte b) =>
			new SecureByte((byte)(a.Decrypted & b.Decrypted));

		/// <summary>Computes the bitwise OR of two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator |(SecureByte a, SecureByte b) =>
			new SecureByte((byte)(a.Decrypted | b.Decrypted));

		/// <summary>Computes the bitwise XOR of two secured byte values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator ^(SecureByte a, SecureByte b) =>
			new SecureByte((byte)(a.Decrypted ^ b.Decrypted));

		/// <summary>Adds a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator +(SecureByte a, byte b) =>
			new SecureInt(a.Decrypted + b);

		/// <summary>Adds a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator +(byte a, SecureByte b) =>
			new SecureInt(a + b.Decrypted);

		/// <summary>Subtracts a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator -(SecureByte a, byte b) =>
			new SecureInt(a.Decrypted - b);

		/// <summary>Subtracts a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator -(byte a, SecureByte b) =>
			new SecureInt(a - b.Decrypted);

		/// <summary>Multiplies a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator *(SecureByte a, byte b) =>
			new SecureInt(a.Decrypted * b);

		/// <summary>Multiplies a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator *(byte a, SecureByte b) =>
			new SecureInt(a * b.Decrypted);

		/// <summary>Divides a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator /(SecureByte a, byte b) =>
			new SecureInt(a.Decrypted / b);

		/// <summary>Divides a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator /(byte a, SecureByte b) =>
			new SecureInt(a / b.Decrypted);

		/// <summary>Remainders a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator %(SecureByte a, byte b) =>
			new SecureInt(a.Decrypted % b);

		/// <summary>Remainders a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator %(byte a, SecureByte b) =>
			new SecureInt(a % b.Decrypted);

		/// <summary>Tests a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureByte a, byte b) =>
			a.Decrypted == b;

		/// <summary>Tests a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(byte a, SecureByte b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureByte a, byte b) =>
			a.Decrypted != b;

		/// <summary>Tests a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(byte a, SecureByte b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureByte a, byte b) =>
			a.Decrypted < b;

		/// <summary>Compares a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(byte a, SecureByte b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureByte a, byte b) =>
			a.Decrypted <= b;

		/// <summary>Compares a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(byte a, SecureByte b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureByte a, byte b) =>
			a.Decrypted > b;

		/// <summary>Compares a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(byte a, SecureByte b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureByte a, byte b) =>
			a.Decrypted >= b;

		/// <summary>Compares a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(byte a, SecureByte b) =>
			a >= b.Decrypted;

		/// <summary>ANDs a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator &(SecureByte a, byte b) =>
			new SecureInt(a.Decrypted & b);

		/// <summary>ANDs a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator &(byte a, SecureByte b) =>
			new SecureInt(a & b.Decrypted);

		/// <summary>ORs a secured byte value and a byte.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator |(SecureByte a, byte b) =>
			new SecureInt(Bits.Or(a.Decrypted, b));

		/// <summary>ORs a byte and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator |(byte a, SecureByte b) =>
			new SecureInt(Bits.Or(a, b.Decrypted));

		/// <summary>Adds a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator +(SecureByte a, int b) =>
			new SecureInt(a.Decrypted + b);

		/// <summary>Adds an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator +(int a, SecureByte b) =>
			new SecureInt(a + b.Decrypted);

		/// <summary>Subtracts a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator -(SecureByte a, int b) =>
			new SecureInt(a.Decrypted - b);

		/// <summary>Subtracts an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator -(int a, SecureByte b) =>
			new SecureInt(a - b.Decrypted);

		/// <summary>Multiplies a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator *(SecureByte a, int b) =>
			new SecureInt(a.Decrypted * b);

		/// <summary>Multiplies an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator *(int a, SecureByte b) =>
			new SecureInt(a * b.Decrypted);

		/// <summary>Divides a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator /(SecureByte a, int b) =>
			new SecureInt(a.Decrypted / b);

		/// <summary>Divides an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator /(int a, SecureByte b) =>
			new SecureInt(a / b.Decrypted);

		/// <summary>Remainders a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator %(SecureByte a, int b) =>
			new SecureInt(a.Decrypted % b);

		/// <summary>Remainders an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator %(int a, SecureByte b) =>
			new SecureInt(a % b.Decrypted);

		/// <summary>Tests a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureByte a, int b) =>
			a.Decrypted == b;

		/// <summary>Tests an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(int a, SecureByte b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureByte a, int b) =>
			a.Decrypted != b;

		/// <summary>Tests an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(int a, SecureByte b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureByte a, int b) =>
			a.Decrypted < b;

		/// <summary>Compares an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(int a, SecureByte b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureByte a, int b) =>
			a.Decrypted <= b;

		/// <summary>Compares an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(int a, SecureByte b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureByte a, int b) =>
			a.Decrypted > b;

		/// <summary>Compares an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(int a, SecureByte b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureByte a, int b) =>
			a.Decrypted >= b;

		/// <summary>Compares an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(int a, SecureByte b) =>
			a >= b.Decrypted;

		/// <summary>ANDs a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator &(SecureByte a, int b) =>
			new SecureInt(a.Decrypted & b);

		/// <summary>ANDs an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator &(int a, SecureByte b) =>
			new SecureInt(a & b.Decrypted);

		/// <summary>ORs a secured byte value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator |(SecureByte a, int b) =>
			new SecureInt(Bits.Or(a.Decrypted, b));

		/// <summary>ORs an int and a secured byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator |(int a, SecureByte b) =>
			new SecureInt(Bits.Or(a, b.Decrypted));

		/// <summary>Shifts a secured byte value left by a plain amount.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator <<(SecureByte a, int b) =>
			new SecureByte((byte)(a.Decrypted << b));

		/// <summary>Shifts a secured byte value right by a plain amount.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureByte operator >>(SecureByte a, int b) =>
			new SecureByte((byte)(a.Decrypted >> b));

		/// <summary>Converts a secured byte value into its secured sbyte form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureSByte(SecureByte value) =>
			new SecureSByte((sbyte)value.Decrypted);

		/// <summary>Converts a secured byte value into its sbyte form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator sbyte(SecureByte value) =>
			(sbyte)value.Decrypted;

		/// <summary>Converts a secured byte value into its secured short form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureShort(SecureByte value) =>
			new SecureShort((short)value.Decrypted);

		/// <summary>Converts a secured byte value into its short form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator short(SecureByte value) =>
			(short)value.Decrypted;

		/// <summary>Converts a secured byte value into its secured ushort form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureUShort(SecureByte value) =>
			new SecureUShort((ushort)value.Decrypted);

		/// <summary>Converts a secured byte value into its ushort form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator ushort(SecureByte value) =>
			(ushort)value.Decrypted;

		/// <summary>Converts a secured byte value into its secured int form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureInt(SecureByte value) =>
			new SecureInt((int)value.Decrypted);

		/// <summary>Converts a secured byte value into its int form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator int(SecureByte value) =>
			(int)value.Decrypted;

		/// <summary>Converts a secured byte value into its secured uint form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureUInt(SecureByte value) =>
			new SecureUInt((uint)value.Decrypted);

		/// <summary>Converts a secured byte value into its uint form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator uint(SecureByte value) =>
			(uint)value.Decrypted;

		/// <summary>Converts a secured byte value into its secured long form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureLong(SecureByte value) =>
			new SecureLong((long)value.Decrypted);

		/// <summary>Converts a secured byte value into its long form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator long(SecureByte value) =>
			(long)value.Decrypted;

		/// <summary>Converts a secured byte value into its secured ulong form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureULong(SecureByte value) =>
			new SecureULong((ulong)value.Decrypted);

		/// <summary>Converts a secured byte value into its ulong form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator ulong(SecureByte value) =>
			(ulong)value.Decrypted;

		/// <summary>Converts a secured byte value into its secured char form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureChar(SecureByte value) =>
			new SecureChar((char)value.Decrypted);

		/// <summary>Converts a secured byte value into its char form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator char(SecureByte value) =>
			(char)value.Decrypted;

		/// <summary>Converts a secured byte value into its secured float form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureFloat(SecureByte value) =>
			new SecureFloat((float)value.Decrypted);

		/// <summary>Converts a secured byte value into its float form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator float(SecureByte value) =>
			(float)value.Decrypted;

		/// <summary>Converts a secured byte value into its secured double form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureDouble(SecureByte value) =>
			new SecureDouble((double)value.Decrypted);

		/// <summary>Converts a secured byte value into its double form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator double(SecureByte value) =>
			(double)value.Decrypted;

		/// <summary>Converts a secured byte value into its secured decimal form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureDecimal(SecureByte value) =>
			new SecureDecimal((decimal)value.Decrypted);

		/// <summary>Converts a secured byte value into its decimal form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator decimal(SecureByte value) =>
			(decimal)value.Decrypted;

		/// <summary>Compares the decrypted value with a plain byte value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<byte>.Equals(byte other) =>
			Decrypted.Equals(other);

		/// <summary>Compares the decrypted value with a plain byte value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IComparable<byte>.CompareTo(byte other) =>
			Decrypted.CompareTo(other);

		/// <summary>Returns the type code of the wrapped primitive type.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		TypeCode IConvertible.GetTypeCode() => Convert.GetTypeCode(Decrypted);

		/// <summary>Converts the decrypted value to bool (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IConvertible.ToBoolean(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToBoolean(provider);

		/// <summary>Converts the decrypted value to byte (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		byte IConvertible.ToByte(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToByte(provider);

		/// <summary>Converts the decrypted value to sbyte (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		sbyte IConvertible.ToSByte(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToSByte(provider);

		/// <summary>Converts the decrypted value to short (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		short IConvertible.ToInt16(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt16(provider);

		/// <summary>Converts the decrypted value to ushort (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		ushort IConvertible.ToUInt16(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt16(provider);

		/// <summary>Converts the decrypted value to int (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IConvertible.ToInt32(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt32(provider);

		/// <summary>Converts the decrypted value to uint (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		uint IConvertible.ToUInt32(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt32(provider);

		/// <summary>Converts the decrypted value to long (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		long IConvertible.ToInt64(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt64(provider);

		/// <summary>Converts the decrypted value to ulong (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		ulong IConvertible.ToUInt64(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt64(provider);

		/// <summary>Converts the decrypted value to float (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		float IConvertible.ToSingle(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToSingle(provider);

		/// <summary>Converts the decrypted value to double (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		double IConvertible.ToDouble(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDouble(provider);

		/// <summary>Converts the decrypted value to decimal (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		decimal IConvertible.ToDecimal(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDecimal(provider);

		/// <summary>Converts the decrypted value to DateTime (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		DateTime IConvertible.ToDateTime(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDateTime(provider);

		/// <summary>Converts the decrypted value to char (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		char IConvertible.ToChar(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToChar(provider);

		/// <summary>Converts the decrypted value to a string (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		string IConvertible.ToString(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToString(provider);

		/// <summary>Converts the decrypted value to the specified type (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		object IConvertible.ToType(Type conversionType, IFormatProvider provider) =>
			((IConvertible)Decrypted).ToType(conversionType, provider);
#if NET6_0_OR_GREATER
		/// <summary>Tries to format the decrypted value into the destination span.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			Decrypted.TryFormat(destination, out charsWritten, format, provider);
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureByte parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureByte System.IParsable<SecureByte>.Parse(string s, IFormatProvider provider) =>
			new SecureByte(byte.Parse(s, provider));

		/// <summary>Tries to parse input into its secured form (explicit SecureByte parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IParsable<SecureByte>.TryParse(string s, IFormatProvider provider, out SecureByte result)
		{
			if (byte.TryParse(s, provider, out byte plain))
			{
				result = new SecureByte(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureByte parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureByte System.ISpanParsable<SecureByte>.Parse(ReadOnlySpan<char> s, IFormatProvider provider)
		{
			if (byte.TryParse(s, provider, out byte plain))
			{
				return new SecureByte(plain);
			}

			throw new System.FormatException("Input was not in a correct format.");
		}

		/// <summary>Tries to parse input into its secured form (explicit SecureByte parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.ISpanParsable<SecureByte>.TryParse(ReadOnlySpan<char> s, IFormatProvider provider, out SecureByte result)
		{
			if (byte.TryParse(s, provider, out byte plain))
			{
				result = new SecureByte(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureByte parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureByte System.IUtf8SpanParsable<SecureByte>.Parse(ReadOnlySpan<byte> s, IFormatProvider provider)
		{
			if (byte.TryParse(s, provider, out byte plain))
			{
				return new SecureByte(plain);
			}

			throw new System.FormatException("Input was not in a correct format.");
		}

		/// <summary>Tries to parse input into its secured form (explicit SecureByte parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IUtf8SpanParsable<SecureByte>.TryParse(ReadOnlySpan<byte> s, IFormatProvider provider, out SecureByte result)
		{
			if (byte.TryParse(s, provider, out byte plain))
			{
				result = new SecureByte(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Tries to format the decrypted value as UTF-8 bytes.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			((System.IUtf8SpanFormattable)Decrypted).TryFormat(utf8Destination, out bytesWritten, format, provider);
#endif
	}
}
