// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
using System;
using System.Runtime.CompilerServices;

namespace SecureValue
{
	public partial struct SecureDouble : IComparable, IComparable<SecureDouble>, IComparable<double>, IConvertible, IEquatable<SecureDouble>, IEquatable<double>, IFormattable, ISecureValue<double>
#if NET6_0_OR_GREATER
			,
			ISpanFormattable
#endif
#if NET7_0_OR_GREATER
			,
			IParsable<SecureDouble>,
			ISpanParsable<SecureDouble>
#endif
#if NET8_0_OR_GREATER
			,
			IUtf8SpanFormattable,
			IUtf8SpanParsable<SecureDouble>
#endif
	{
		/// <summary>Tests two secured double values for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureDouble left, SecureDouble right) =>
			left.Equals(right);

		/// <summary>Tests two secured double values for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureDouble left, SecureDouble right) =>
			!left.Equals(right);

		/// <summary>Compares two secured double values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureDouble left, SecureDouble right) =>
			left.Decrypted < right.Decrypted;

		/// <summary>Compares two secured double values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureDouble left, SecureDouble right) =>
			left.Decrypted <= right.Decrypted;

		/// <summary>Compares two secured double values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureDouble left, SecureDouble right) =>
			left.Decrypted > right.Decrypted;

		/// <summary>Compares two secured double values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureDouble left, SecureDouble right) =>
			left.Decrypted >= right.Decrypted;

		/// <summary>Adds two secured double values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator +(SecureDouble a, SecureDouble b) =>
			new SecureDouble((double)(a.Decrypted + b.Decrypted));

		/// <summary>Subtracts two secured double values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator -(SecureDouble a, SecureDouble b) =>
			new SecureDouble((double)(a.Decrypted - b.Decrypted));

		/// <summary>Multiplies two secured double values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator *(SecureDouble a, SecureDouble b) =>
			new SecureDouble((double)(a.Decrypted * b.Decrypted));

		/// <summary>Divides two secured double values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator /(SecureDouble a, SecureDouble b) =>
			new SecureDouble((double)(a.Decrypted / b.Decrypted));

		/// <summary>Remainders two secured double values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator %(SecureDouble a, SecureDouble b) =>
			new SecureDouble((double)(a.Decrypted % b.Decrypted));

		/// <summary>Negates a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator -(SecureDouble a) =>
			new SecureDouble((double)(-a.Decrypted));

		/// <summary>Applies unary plus to a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator +(SecureDouble a) =>
			new SecureDouble((double)(+a.Decrypted));

		/// <summary>Increments a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator ++(SecureDouble a) =>
			new SecureDouble((double)(a.Decrypted + 1));

		/// <summary>Decrements a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator --(SecureDouble a) =>
			new SecureDouble((double)(a.Decrypted - 1));

		/// <summary>Adds a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator +(SecureDouble a, double b) =>
			new SecureDouble(a.Decrypted + b);

		/// <summary>Adds a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator +(double a, SecureDouble b) =>
			new SecureDouble(a + b.Decrypted);

		/// <summary>Subtracts a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator -(SecureDouble a, double b) =>
			new SecureDouble(a.Decrypted - b);

		/// <summary>Subtracts a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator -(double a, SecureDouble b) =>
			new SecureDouble(a - b.Decrypted);

		/// <summary>Multiplies a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator *(SecureDouble a, double b) =>
			new SecureDouble(a.Decrypted * b);

		/// <summary>Multiplies a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator *(double a, SecureDouble b) =>
			new SecureDouble(a * b.Decrypted);

		/// <summary>Divides a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator /(SecureDouble a, double b) =>
			new SecureDouble(a.Decrypted / b);

		/// <summary>Divides a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator /(double a, SecureDouble b) =>
			new SecureDouble(a / b.Decrypted);

		/// <summary>Remainders a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator %(SecureDouble a, double b) =>
			new SecureDouble(a.Decrypted % b);

		/// <summary>Remainders a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator %(double a, SecureDouble b) =>
			new SecureDouble(a % b.Decrypted);

		/// <summary>Tests a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureDouble a, double b) =>
			a.Decrypted == b;

		/// <summary>Tests a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(double a, SecureDouble b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureDouble a, double b) =>
			a.Decrypted != b;

		/// <summary>Tests a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(double a, SecureDouble b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureDouble a, double b) =>
			a.Decrypted < b;

		/// <summary>Compares a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(double a, SecureDouble b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureDouble a, double b) =>
			a.Decrypted <= b;

		/// <summary>Compares a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(double a, SecureDouble b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureDouble a, double b) =>
			a.Decrypted > b;

		/// <summary>Compares a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(double a, SecureDouble b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured double value and a double.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureDouble a, double b) =>
			a.Decrypted >= b;

		/// <summary>Compares a double and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(double a, SecureDouble b) =>
			a >= b.Decrypted;

		/// <summary>Adds a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator +(SecureDouble a, int b) =>
			new SecureDouble(a.Decrypted + b);

		/// <summary>Adds an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator +(int a, SecureDouble b) =>
			new SecureDouble(a + b.Decrypted);

		/// <summary>Subtracts a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator -(SecureDouble a, int b) =>
			new SecureDouble(a.Decrypted - b);

		/// <summary>Subtracts an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator -(int a, SecureDouble b) =>
			new SecureDouble(a - b.Decrypted);

		/// <summary>Multiplies a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator *(SecureDouble a, int b) =>
			new SecureDouble(a.Decrypted * b);

		/// <summary>Multiplies an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator *(int a, SecureDouble b) =>
			new SecureDouble(a * b.Decrypted);

		/// <summary>Divides a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator /(SecureDouble a, int b) =>
			new SecureDouble(a.Decrypted / b);

		/// <summary>Divides an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator /(int a, SecureDouble b) =>
			new SecureDouble(a / b.Decrypted);

		/// <summary>Remainders a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator %(SecureDouble a, int b) =>
			new SecureDouble(a.Decrypted % b);

		/// <summary>Remainders an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDouble operator %(int a, SecureDouble b) =>
			new SecureDouble(a % b.Decrypted);

		/// <summary>Tests a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureDouble a, int b) =>
			a.Decrypted == b;

		/// <summary>Tests an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(int a, SecureDouble b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureDouble a, int b) =>
			a.Decrypted != b;

		/// <summary>Tests an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(int a, SecureDouble b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureDouble a, int b) =>
			a.Decrypted < b;

		/// <summary>Compares an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(int a, SecureDouble b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureDouble a, int b) =>
			a.Decrypted <= b;

		/// <summary>Compares an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(int a, SecureDouble b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureDouble a, int b) =>
			a.Decrypted > b;

		/// <summary>Compares an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(int a, SecureDouble b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured double value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureDouble a, int b) =>
			a.Decrypted >= b;

		/// <summary>Compares an int and a secured double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(int a, SecureDouble b) =>
			a >= b.Decrypted;

		/// <summary>Converts a secured double value into its secured sbyte form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureSByte(SecureDouble value) =>
			new SecureSByte((sbyte)value.Decrypted);

		/// <summary>Converts a secured double value into its secured byte form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureByte(SecureDouble value) =>
			new SecureByte((byte)value.Decrypted);

		/// <summary>Converts a secured double value into its secured short form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureShort(SecureDouble value) =>
			new SecureShort((short)value.Decrypted);

		/// <summary>Converts a secured double value into its secured ushort form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureUShort(SecureDouble value) =>
			new SecureUShort((ushort)value.Decrypted);

		/// <summary>Converts a secured double value into its secured int form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureInt(SecureDouble value) =>
			new SecureInt((int)value.Decrypted);

		/// <summary>Converts a secured double value into its secured uint form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureUInt(SecureDouble value) =>
			new SecureUInt((uint)value.Decrypted);

		/// <summary>Converts a secured double value into its secured long form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureLong(SecureDouble value) =>
			new SecureLong((long)value.Decrypted);

		/// <summary>Converts a secured double value into its secured ulong form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureULong(SecureDouble value) =>
			new SecureULong((ulong)value.Decrypted);

		/// <summary>Converts a secured double value into its secured char form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureChar(SecureDouble value) =>
			new SecureChar((char)value.Decrypted);

		/// <summary>Converts a secured double value into its secured float form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureFloat(SecureDouble value) =>
			new SecureFloat((float)value.Decrypted);

		/// <summary>Converts a secured double value into its secured decimal form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureDecimal(SecureDouble value) =>
			new SecureDecimal((decimal)value.Decrypted);

		/// <summary>Compares the decrypted value with a plain double value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<double>.Equals(double other) =>
			Decrypted.Equals(other);

		/// <summary>Compares the decrypted value with a plain double value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IComparable<double>.CompareTo(double other) =>
			Decrypted.CompareTo(other);

		/// <summary>Returns the type code of the wrapped primitive type.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		TypeCode IConvertible.GetTypeCode() => Convert.GetTypeCode(Decrypted);

		/// <summary>Converts the decrypted value to bool (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IConvertible.ToBoolean(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToBoolean(provider);

		/// <summary>Converts the decrypted value to byte (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		byte IConvertible.ToByte(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToByte(provider);

		/// <summary>Converts the decrypted value to sbyte (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		sbyte IConvertible.ToSByte(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToSByte(provider);

		/// <summary>Converts the decrypted value to short (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		short IConvertible.ToInt16(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt16(provider);

		/// <summary>Converts the decrypted value to ushort (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		ushort IConvertible.ToUInt16(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt16(provider);

		/// <summary>Converts the decrypted value to int (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IConvertible.ToInt32(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt32(provider);

		/// <summary>Converts the decrypted value to uint (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		uint IConvertible.ToUInt32(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt32(provider);

		/// <summary>Converts the decrypted value to long (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		long IConvertible.ToInt64(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt64(provider);

		/// <summary>Converts the decrypted value to ulong (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		ulong IConvertible.ToUInt64(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt64(provider);

		/// <summary>Converts the decrypted value to float (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		float IConvertible.ToSingle(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToSingle(provider);

		/// <summary>Converts the decrypted value to double (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		double IConvertible.ToDouble(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDouble(provider);

		/// <summary>Converts the decrypted value to decimal (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		decimal IConvertible.ToDecimal(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDecimal(provider);

		/// <summary>Converts the decrypted value to DateTime (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		DateTime IConvertible.ToDateTime(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDateTime(provider);

		/// <summary>Converts the decrypted value to char (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		char IConvertible.ToChar(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToChar(provider);

		/// <summary>Converts the decrypted value to a string (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		string IConvertible.ToString(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToString(provider);

		/// <summary>Converts the decrypted value to the specified type (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		object IConvertible.ToType(Type conversionType, IFormatProvider provider) =>
			((IConvertible)Decrypted).ToType(conversionType, provider);
#if NET6_0_OR_GREATER
		/// <summary>Tries to format the decrypted value into the destination span.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			Decrypted.TryFormat(destination, out charsWritten, format, provider);
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureDouble parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureDouble System.IParsable<SecureDouble>.Parse(string s, IFormatProvider provider) =>
			new SecureDouble(double.Parse(s, provider));

		/// <summary>Tries to parse input into its secured form (explicit SecureDouble parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IParsable<SecureDouble>.TryParse(string s, IFormatProvider provider, out SecureDouble result)
		{
			if (double.TryParse(s, provider, out double plain))
			{
				result = new SecureDouble(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureDouble parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureDouble System.ISpanParsable<SecureDouble>.Parse(ReadOnlySpan<char> s, IFormatProvider provider)
		{
			if (double.TryParse(s, provider, out double plain))
			{
				return new SecureDouble(plain);
			}

			throw new System.FormatException("Input was not in a correct format.");
		}

		/// <summary>Tries to parse input into its secured form (explicit SecureDouble parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.ISpanParsable<SecureDouble>.TryParse(ReadOnlySpan<char> s, IFormatProvider provider, out SecureDouble result)
		{
			if (double.TryParse(s, provider, out double plain))
			{
				result = new SecureDouble(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureDouble parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureDouble System.IUtf8SpanParsable<SecureDouble>.Parse(ReadOnlySpan<byte> s, IFormatProvider provider)
		{
			if (double.TryParse(s, provider, out double plain))
			{
				return new SecureDouble(plain);
			}

			throw new System.FormatException("Input was not in a correct format.");
		}

		/// <summary>Tries to parse input into its secured form (explicit SecureDouble parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IUtf8SpanParsable<SecureDouble>.TryParse(ReadOnlySpan<byte> s, IFormatProvider provider, out SecureDouble result)
		{
			if (double.TryParse(s, provider, out double plain))
			{
				result = new SecureDouble(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Tries to format the decrypted value as UTF-8 bytes.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			((System.IUtf8SpanFormattable)Decrypted).TryFormat(utf8Destination, out bytesWritten, format, provider);
#endif
	}
}
