// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
using System;
using System.Runtime.CompilerServices;

namespace SecureValue
{
	public partial struct SecureDecimal : IComparable, IComparable<SecureDecimal>, IComparable<decimal>, IConvertible, IEquatable<SecureDecimal>, IEquatable<decimal>, IFormattable, ISecureValue<decimal>
#if NET6_0_OR_GREATER
			,
			ISpanFormattable
#endif
#if NET7_0_OR_GREATER
			,
			IParsable<SecureDecimal>,
			ISpanParsable<SecureDecimal>
#endif
#if NET8_0_OR_GREATER
			,
			IUtf8SpanFormattable,
			IUtf8SpanParsable<SecureDecimal>
#endif
	{
		/// <summary>Tests two secured decimal values for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureDecimal left, SecureDecimal right) =>
			left.Equals(right);

		/// <summary>Tests two secured decimal values for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureDecimal left, SecureDecimal right) =>
			!left.Equals(right);

		/// <summary>Compares two secured decimal values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureDecimal left, SecureDecimal right) =>
			left.Decrypted < right.Decrypted;

		/// <summary>Compares two secured decimal values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureDecimal left, SecureDecimal right) =>
			left.Decrypted <= right.Decrypted;

		/// <summary>Compares two secured decimal values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureDecimal left, SecureDecimal right) =>
			left.Decrypted > right.Decrypted;

		/// <summary>Compares two secured decimal values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureDecimal left, SecureDecimal right) =>
			left.Decrypted >= right.Decrypted;

		/// <summary>Adds two secured decimal values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator +(SecureDecimal a, SecureDecimal b) =>
			new SecureDecimal(a.Decrypted + b.Decrypted);

		/// <summary>Subtracts two secured decimal values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator -(SecureDecimal a, SecureDecimal b) =>
			new SecureDecimal(a.Decrypted - b.Decrypted);

		/// <summary>Multiplies two secured decimal values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator *(SecureDecimal a, SecureDecimal b) =>
			new SecureDecimal(a.Decrypted * b.Decrypted);

		/// <summary>Divides two secured decimal values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator /(SecureDecimal a, SecureDecimal b) =>
			new SecureDecimal(a.Decrypted / b.Decrypted);

		/// <summary>Remainders two secured decimal values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator %(SecureDecimal a, SecureDecimal b) =>
			new SecureDecimal(a.Decrypted % b.Decrypted);

		/// <summary>Negates a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator -(SecureDecimal a) =>
			new SecureDecimal(-a.Decrypted);

		/// <summary>Applies unary plus to a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator +(SecureDecimal a) =>
			new SecureDecimal(+a.Decrypted);

		/// <summary>Increments a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator ++(SecureDecimal a) =>
			new SecureDecimal(a.Decrypted + 1);

		/// <summary>Decrements a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator --(SecureDecimal a) =>
			new SecureDecimal(a.Decrypted - 1);

		/// <summary>Adds a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator +(SecureDecimal a, decimal b) =>
			new SecureDecimal(a.Decrypted + b);

		/// <summary>Adds a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator +(decimal a, SecureDecimal b) =>
			new SecureDecimal(a + b.Decrypted);

		/// <summary>Subtracts a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator -(SecureDecimal a, decimal b) =>
			new SecureDecimal(a.Decrypted - b);

		/// <summary>Subtracts a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator -(decimal a, SecureDecimal b) =>
			new SecureDecimal(a - b.Decrypted);

		/// <summary>Multiplies a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator *(SecureDecimal a, decimal b) =>
			new SecureDecimal(a.Decrypted * b);

		/// <summary>Multiplies a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator *(decimal a, SecureDecimal b) =>
			new SecureDecimal(a * b.Decrypted);

		/// <summary>Divides a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator /(SecureDecimal a, decimal b) =>
			new SecureDecimal(a.Decrypted / b);

		/// <summary>Divides a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator /(decimal a, SecureDecimal b) =>
			new SecureDecimal(a / b.Decrypted);

		/// <summary>Remainders a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator %(SecureDecimal a, decimal b) =>
			new SecureDecimal(a.Decrypted % b);

		/// <summary>Remainders a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator %(decimal a, SecureDecimal b) =>
			new SecureDecimal(a % b.Decrypted);

		/// <summary>Tests a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureDecimal a, decimal b) =>
			a.Decrypted == b;

		/// <summary>Tests a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(decimal a, SecureDecimal b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureDecimal a, decimal b) =>
			a.Decrypted != b;

		/// <summary>Tests a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(decimal a, SecureDecimal b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureDecimal a, decimal b) =>
			a.Decrypted < b;

		/// <summary>Compares a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(decimal a, SecureDecimal b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureDecimal a, decimal b) =>
			a.Decrypted <= b;

		/// <summary>Compares a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(decimal a, SecureDecimal b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureDecimal a, decimal b) =>
			a.Decrypted > b;

		/// <summary>Compares a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(decimal a, SecureDecimal b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured decimal value and a decimal.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureDecimal a, decimal b) =>
			a.Decrypted >= b;

		/// <summary>Compares a decimal and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(decimal a, SecureDecimal b) =>
			a >= b.Decrypted;

		/// <summary>Adds a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator +(SecureDecimal a, int b) =>
			new SecureDecimal(a.Decrypted + b);

		/// <summary>Adds an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator +(int a, SecureDecimal b) =>
			new SecureDecimal(a + b.Decrypted);

		/// <summary>Subtracts a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator -(SecureDecimal a, int b) =>
			new SecureDecimal(a.Decrypted - b);

		/// <summary>Subtracts an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator -(int a, SecureDecimal b) =>
			new SecureDecimal(a - b.Decrypted);

		/// <summary>Multiplies a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator *(SecureDecimal a, int b) =>
			new SecureDecimal(a.Decrypted * b);

		/// <summary>Multiplies an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator *(int a, SecureDecimal b) =>
			new SecureDecimal(a * b.Decrypted);

		/// <summary>Divides a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator /(SecureDecimal a, int b) =>
			new SecureDecimal(a.Decrypted / b);

		/// <summary>Divides an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator /(int a, SecureDecimal b) =>
			new SecureDecimal(a / b.Decrypted);

		/// <summary>Remainders a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator %(SecureDecimal a, int b) =>
			new SecureDecimal(a.Decrypted % b);

		/// <summary>Remainders an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureDecimal operator %(int a, SecureDecimal b) =>
			new SecureDecimal(a % b.Decrypted);

		/// <summary>Tests a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureDecimal a, int b) =>
			a.Decrypted == b;

		/// <summary>Tests an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(int a, SecureDecimal b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureDecimal a, int b) =>
			a.Decrypted != b;

		/// <summary>Tests an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(int a, SecureDecimal b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureDecimal a, int b) =>
			a.Decrypted < b;

		/// <summary>Compares an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(int a, SecureDecimal b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureDecimal a, int b) =>
			a.Decrypted <= b;

		/// <summary>Compares an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(int a, SecureDecimal b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureDecimal a, int b) =>
			a.Decrypted > b;

		/// <summary>Compares an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(int a, SecureDecimal b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured decimal value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureDecimal a, int b) =>
			a.Decrypted >= b;

		/// <summary>Compares an int and a secured decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(int a, SecureDecimal b) =>
			a >= b.Decrypted;

		/// <summary>Converts a secured decimal value into its secured sbyte form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureSByte(SecureDecimal value) =>
			new SecureSByte((sbyte)value.Decrypted);

		/// <summary>Converts a secured decimal value into its sbyte form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator sbyte(SecureDecimal value) =>
			(sbyte)value.Decrypted;

		/// <summary>Converts a secured decimal value into its secured byte form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureByte(SecureDecimal value) =>
			new SecureByte((byte)value.Decrypted);

		/// <summary>Converts a secured decimal value into its byte form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator byte(SecureDecimal value) =>
			(byte)value.Decrypted;

		/// <summary>Converts a secured decimal value into its secured short form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureShort(SecureDecimal value) =>
			new SecureShort((short)value.Decrypted);

		/// <summary>Converts a secured decimal value into its short form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator short(SecureDecimal value) =>
			(short)value.Decrypted;

		/// <summary>Converts a secured decimal value into its secured ushort form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureUShort(SecureDecimal value) =>
			new SecureUShort((ushort)value.Decrypted);

		/// <summary>Converts a secured decimal value into its ushort form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator ushort(SecureDecimal value) =>
			(ushort)value.Decrypted;

		/// <summary>Converts a secured decimal value into its secured int form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureInt(SecureDecimal value) =>
			new SecureInt((int)value.Decrypted);

		/// <summary>Converts a secured decimal value into its int form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator int(SecureDecimal value) =>
			(int)value.Decrypted;

		/// <summary>Converts a secured decimal value into its secured uint form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureUInt(SecureDecimal value) =>
			new SecureUInt((uint)value.Decrypted);

		/// <summary>Converts a secured decimal value into its uint form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator uint(SecureDecimal value) =>
			(uint)value.Decrypted;

		/// <summary>Converts a secured decimal value into its secured long form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureLong(SecureDecimal value) =>
			new SecureLong((long)value.Decrypted);

		/// <summary>Converts a secured decimal value into its long form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator long(SecureDecimal value) =>
			(long)value.Decrypted;

		/// <summary>Converts a secured decimal value into its secured ulong form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureULong(SecureDecimal value) =>
			new SecureULong((ulong)value.Decrypted);

		/// <summary>Converts a secured decimal value into its ulong form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator ulong(SecureDecimal value) =>
			(ulong)value.Decrypted;

		/// <summary>Converts a secured decimal value into its secured char form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureChar(SecureDecimal value) =>
			new SecureChar((char)value.Decrypted);

		/// <summary>Converts a secured decimal value into its char form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator char(SecureDecimal value) =>
			(char)value.Decrypted;

		/// <summary>Converts a secured decimal value into its secured float form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureFloat(SecureDecimal value) =>
			new SecureFloat((float)value.Decrypted);

		/// <summary>Converts a secured decimal value into its float form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator float(SecureDecimal value) =>
			(float)value.Decrypted;

		/// <summary>Converts a secured decimal value into its secured double form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureDouble(SecureDecimal value) =>
			new SecureDouble((double)value.Decrypted);

		/// <summary>Converts a secured decimal value into its double form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator double(SecureDecimal value) =>
			(double)value.Decrypted;

		/// <summary>Compares the decrypted value with a plain decimal value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<decimal>.Equals(decimal other) =>
			Decrypted.Equals(other);

		/// <summary>Compares the decrypted value with a plain decimal value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IComparable<decimal>.CompareTo(decimal other) =>
			Decrypted.CompareTo(other);

		/// <summary>Returns the type code of the wrapped primitive type.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		TypeCode IConvertible.GetTypeCode() => Convert.GetTypeCode(Decrypted);

		/// <summary>Converts the decrypted value to bool (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IConvertible.ToBoolean(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToBoolean(provider);

		/// <summary>Converts the decrypted value to byte (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		byte IConvertible.ToByte(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToByte(provider);

		/// <summary>Converts the decrypted value to sbyte (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		sbyte IConvertible.ToSByte(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToSByte(provider);

		/// <summary>Converts the decrypted value to short (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		short IConvertible.ToInt16(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt16(provider);

		/// <summary>Converts the decrypted value to ushort (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		ushort IConvertible.ToUInt16(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt16(provider);

		/// <summary>Converts the decrypted value to int (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IConvertible.ToInt32(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt32(provider);

		/// <summary>Converts the decrypted value to uint (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		uint IConvertible.ToUInt32(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt32(provider);

		/// <summary>Converts the decrypted value to long (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		long IConvertible.ToInt64(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt64(provider);

		/// <summary>Converts the decrypted value to ulong (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		ulong IConvertible.ToUInt64(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt64(provider);

		/// <summary>Converts the decrypted value to float (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		float IConvertible.ToSingle(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToSingle(provider);

		/// <summary>Converts the decrypted value to double (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		double IConvertible.ToDouble(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDouble(provider);

		/// <summary>Converts the decrypted value to decimal (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		decimal IConvertible.ToDecimal(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDecimal(provider);

		/// <summary>Converts the decrypted value to DateTime (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		DateTime IConvertible.ToDateTime(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDateTime(provider);

		/// <summary>Converts the decrypted value to char (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		char IConvertible.ToChar(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToChar(provider);

		/// <summary>Converts the decrypted value to a string (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		string IConvertible.ToString(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToString(provider);

		/// <summary>Converts the decrypted value to the specified type (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		object IConvertible.ToType(Type conversionType, IFormatProvider provider) =>
			((IConvertible)Decrypted).ToType(conversionType, provider);
#if NET6_0_OR_GREATER
		/// <summary>Tries to format the decrypted value into the destination span.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			Decrypted.TryFormat(destination, out charsWritten, format, provider);
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureDecimal parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureDecimal System.IParsable<SecureDecimal>.Parse(string s, IFormatProvider provider) =>
			new SecureDecimal(decimal.Parse(s, provider));

		/// <summary>Tries to parse input into its secured form (explicit SecureDecimal parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IParsable<SecureDecimal>.TryParse(string s, IFormatProvider provider, out SecureDecimal result)
		{
			if (decimal.TryParse(s, provider, out decimal plain))
			{
				result = new SecureDecimal(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureDecimal parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureDecimal System.ISpanParsable<SecureDecimal>.Parse(ReadOnlySpan<char> s, IFormatProvider provider)
		{
			if (decimal.TryParse(s, provider, out decimal plain))
			{
				return new SecureDecimal(plain);
			}

			throw new System.FormatException("Input was not in a correct format.");
		}

		/// <summary>Tries to parse input into its secured form (explicit SecureDecimal parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.ISpanParsable<SecureDecimal>.TryParse(ReadOnlySpan<char> s, IFormatProvider provider, out SecureDecimal result)
		{
			if (decimal.TryParse(s, provider, out decimal plain))
			{
				result = new SecureDecimal(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureDecimal parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureDecimal System.IUtf8SpanParsable<SecureDecimal>.Parse(ReadOnlySpan<byte> s, IFormatProvider provider)
		{
			if (decimal.TryParse(s, provider, out decimal plain))
			{
				return new SecureDecimal(plain);
			}

			throw new System.FormatException("Input was not in a correct format.");
		}

		/// <summary>Tries to parse input into its secured form (explicit SecureDecimal parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IUtf8SpanParsable<SecureDecimal>.TryParse(ReadOnlySpan<byte> s, IFormatProvider provider, out SecureDecimal result)
		{
			if (decimal.TryParse(s, provider, out decimal plain))
			{
				result = new SecureDecimal(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Tries to format the decrypted value as UTF-8 bytes.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			((System.IUtf8SpanFormattable)Decrypted).TryFormat(utf8Destination, out bytesWritten, format, provider);
#endif
	}
}
