// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
using System;
using System.Runtime.CompilerServices;

namespace SecureValue
{
	public partial struct SecureChar : IComparable, IComparable<SecureChar>, IComparable<char>, IConvertible, IEquatable<SecureChar>, IEquatable<char>, IFormattable
#if NET6_0_OR_GREATER
			,
			ISpanFormattable
#endif
#if NET7_0_OR_GREATER
			,
			IParsable<SecureChar>,
			ISpanParsable<SecureChar>
#endif
#if NET8_0_OR_GREATER
			,
			IUtf8SpanFormattable,
			IUtf8SpanParsable<SecureChar>
#endif
	{
		/// <summary>Tests two secured char values for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureChar left, SecureChar right) =>
			left.Equals(right);

		/// <summary>Tests two secured char values for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureChar left, SecureChar right) =>
			!left.Equals(right);

		/// <summary>Compares two secured char values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureChar left, SecureChar right) =>
			left.Decrypted < right.Decrypted;

		/// <summary>Compares two secured char values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureChar left, SecureChar right) =>
			left.Decrypted <= right.Decrypted;

		/// <summary>Compares two secured char values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureChar left, SecureChar right) =>
			left.Decrypted > right.Decrypted;

		/// <summary>Compares two secured char values.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureChar left, SecureChar right) =>
			left.Decrypted >= right.Decrypted;

		/// <summary>Increments a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureChar operator ++(SecureChar a) =>
			new SecureChar((char)(a.Decrypted + 1));

		/// <summary>Decrements a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureChar operator --(SecureChar a) =>
			new SecureChar((char)(a.Decrypted - 1));

		/// <summary>Adds a secured char value and a char.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator +(SecureChar a, char b) =>
			new SecureInt(a.Decrypted + b);

		/// <summary>Adds a char and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator +(char a, SecureChar b) =>
			new SecureInt(a + b.Decrypted);

		/// <summary>Subtracts a secured char value and a char.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator -(SecureChar a, char b) =>
			new SecureInt(a.Decrypted - b);

		/// <summary>Subtracts a char and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator -(char a, SecureChar b) =>
			new SecureInt(a - b.Decrypted);

		/// <summary>Tests a secured char value and a char.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureChar a, char b) =>
			a.Decrypted == b;

		/// <summary>Tests a char and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(char a, SecureChar b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured char value and a char.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureChar a, char b) =>
			a.Decrypted != b;

		/// <summary>Tests a char and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(char a, SecureChar b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured char value and a char.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureChar a, char b) =>
			a.Decrypted < b;

		/// <summary>Compares a char and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(char a, SecureChar b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured char value and a char.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureChar a, char b) =>
			a.Decrypted <= b;

		/// <summary>Compares a char and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(char a, SecureChar b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured char value and a char.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureChar a, char b) =>
			a.Decrypted > b;

		/// <summary>Compares a char and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(char a, SecureChar b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured char value and a char.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureChar a, char b) =>
			a.Decrypted >= b;

		/// <summary>Compares a char and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(char a, SecureChar b) =>
			a >= b.Decrypted;

		/// <summary>ANDs a secured char value and a char.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator &(SecureChar a, char b) =>
			new SecureInt(a.Decrypted & b);

		/// <summary>ANDs a char and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator &(char a, SecureChar b) =>
			new SecureInt(a & b.Decrypted);

		/// <summary>ORs a secured char value and a char.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator |(SecureChar a, char b) =>
			new SecureInt(Bits.Or(a.Decrypted, b));

		/// <summary>ORs a char and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator |(char a, SecureChar b) =>
			new SecureInt(Bits.Or(a, b.Decrypted));

		/// <summary>Adds a secured char value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator +(SecureChar a, int b) =>
			new SecureInt(a.Decrypted + b);

		/// <summary>Adds an int and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator +(int a, SecureChar b) =>
			new SecureInt(a + b.Decrypted);

		/// <summary>Subtracts a secured char value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator -(SecureChar a, int b) =>
			new SecureInt(a.Decrypted - b);

		/// <summary>Subtracts an int and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator -(int a, SecureChar b) =>
			new SecureInt(a - b.Decrypted);

		/// <summary>Tests a secured char value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureChar a, int b) =>
			a.Decrypted == b;

		/// <summary>Tests an int and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(int a, SecureChar b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured char value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureChar a, int b) =>
			a.Decrypted != b;

		/// <summary>Tests an int and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(int a, SecureChar b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured char value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureChar a, int b) =>
			a.Decrypted < b;

		/// <summary>Compares an int and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(int a, SecureChar b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured char value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureChar a, int b) =>
			a.Decrypted <= b;

		/// <summary>Compares an int and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(int a, SecureChar b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured char value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureChar a, int b) =>
			a.Decrypted > b;

		/// <summary>Compares an int and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(int a, SecureChar b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured char value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureChar a, int b) =>
			a.Decrypted >= b;

		/// <summary>Compares an int and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(int a, SecureChar b) =>
			a >= b.Decrypted;

		/// <summary>ANDs a secured char value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator &(SecureChar a, int b) =>
			new SecureInt(a.Decrypted & b);

		/// <summary>ANDs an int and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator &(int a, SecureChar b) =>
			new SecureInt(a & b.Decrypted);

		/// <summary>ORs a secured char value and an int.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator |(SecureChar a, int b) =>
			new SecureInt(Bits.Or(a.Decrypted, b));

		/// <summary>ORs an int and a secured char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static SecureInt operator |(int a, SecureChar b) =>
			new SecureInt(Bits.Or(a, b.Decrypted));

		/// <summary>Converts a secured char value into its secured sbyte form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureSByte(SecureChar value) =>
			new SecureSByte((sbyte)value.Decrypted);

		/// <summary>Converts a secured char value into its secured byte form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureByte(SecureChar value) =>
			new SecureByte((byte)value.Decrypted);

		/// <summary>Converts a secured char value into its secured short form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureShort(SecureChar value) =>
			new SecureShort((short)value.Decrypted);

		/// <summary>Converts a secured char value into its secured ushort form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureUShort(SecureChar value) =>
			new SecureUShort((ushort)value.Decrypted);

		/// <summary>Converts a secured char value into its secured int form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureInt(SecureChar value) =>
			new SecureInt((int)value.Decrypted);

		/// <summary>Converts a secured char value into its secured uint form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureUInt(SecureChar value) =>
			new SecureUInt((uint)value.Decrypted);

		/// <summary>Converts a secured char value into its secured long form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureLong(SecureChar value) =>
			new SecureLong((long)value.Decrypted);

		/// <summary>Converts a secured char value into its secured ulong form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureULong(SecureChar value) =>
			new SecureULong((ulong)value.Decrypted);

		/// <summary>Converts a secured char value into its secured float form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureFloat(SecureChar value) =>
			new SecureFloat((float)value.Decrypted);

		/// <summary>Converts a secured char value into its secured double form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureDouble(SecureChar value) =>
			new SecureDouble((double)value.Decrypted);

		/// <summary>Converts a secured char value into its secured decimal form.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static explicit operator SecureDecimal(SecureChar value) =>
			new SecureDecimal((decimal)value.Decrypted);

		/// <summary>Compares the decrypted value with a plain char value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<char>.Equals(char other) =>
			Decrypted.Equals(other);

		/// <summary>Compares the decrypted value with a plain char value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IComparable<char>.CompareTo(char other) =>
			Decrypted.CompareTo(other);

		/// <summary>Returns the type code of the wrapped primitive type.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		TypeCode IConvertible.GetTypeCode() => Convert.GetTypeCode(Decrypted);

		/// <summary>Converts the decrypted value to bool (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IConvertible.ToBoolean(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToBoolean(provider);

		/// <summary>Converts the decrypted value to byte (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		byte IConvertible.ToByte(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToByte(provider);

		/// <summary>Converts the decrypted value to sbyte (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		sbyte IConvertible.ToSByte(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToSByte(provider);

		/// <summary>Converts the decrypted value to short (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		short IConvertible.ToInt16(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt16(provider);

		/// <summary>Converts the decrypted value to ushort (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		ushort IConvertible.ToUInt16(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt16(provider);

		/// <summary>Converts the decrypted value to int (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IConvertible.ToInt32(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt32(provider);

		/// <summary>Converts the decrypted value to uint (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		uint IConvertible.ToUInt32(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt32(provider);

		/// <summary>Converts the decrypted value to long (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		long IConvertible.ToInt64(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToInt64(provider);

		/// <summary>Converts the decrypted value to ulong (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		ulong IConvertible.ToUInt64(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToUInt64(provider);

		/// <summary>Converts the decrypted value to float (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		float IConvertible.ToSingle(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToSingle(provider);

		/// <summary>Converts the decrypted value to double (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		double IConvertible.ToDouble(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDouble(provider);

		/// <summary>Converts the decrypted value to decimal (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		decimal IConvertible.ToDecimal(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDecimal(provider);

		/// <summary>Converts the decrypted value to DateTime (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		DateTime IConvertible.ToDateTime(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToDateTime(provider);

		/// <summary>Converts the decrypted value to char (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		char IConvertible.ToChar(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToChar(provider);

		/// <summary>Converts the decrypted value to a string (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		string IConvertible.ToString(IFormatProvider provider) =>
			((IConvertible)Decrypted).ToString(provider);

		/// <summary>Converts the decrypted value to the specified type (explicit).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		object IConvertible.ToType(Type conversionType, IFormatProvider provider) =>
			((IConvertible)Decrypted).ToType(conversionType, provider);

		/// <summary>Formats the decrypted value (explicit IFormattable; format is ignored for char).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		string IFormattable.ToString(string format, IFormatProvider provider) => Decrypted.ToString();
#if NET6_0_OR_GREATER
		/// <summary>Tries to format the decrypted value into the destination span.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			((System.ISpanFormattable)Decrypted).TryFormat(destination, out charsWritten, format, provider);
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureChar parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureChar System.IParsable<SecureChar>.Parse(string s, IFormatProvider provider) =>
			new SecureChar(char.Parse(s));

		/// <summary>Tries to parse input into its secured form (explicit SecureChar parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IParsable<SecureChar>.TryParse(string s, IFormatProvider provider, out SecureChar result)
		{
			if (char.TryParse(s, out char plain))
			{
				result = new SecureChar(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureChar parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureChar System.ISpanParsable<SecureChar>.Parse(ReadOnlySpan<char> s, IFormatProvider provider) =>
			new SecureChar(char.Parse(s.ToString()));

		/// <summary>Tries to parse input into its secured form (explicit SecureChar parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.ISpanParsable<SecureChar>.TryParse(ReadOnlySpan<char> s, IFormatProvider provider, out SecureChar result)
		{
			if (char.TryParse(s.ToString(), out char plain))
			{
				result = new SecureChar(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureChar parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureChar System.IUtf8SpanParsable<SecureChar>.Parse(ReadOnlySpan<byte> s, IFormatProvider provider) =>
			new SecureChar(char.Parse(System.Text.Encoding.UTF8.GetString(s)));

		/// <summary>Tries to parse input into its secured form (explicit SecureChar parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IUtf8SpanParsable<SecureChar>.TryParse(ReadOnlySpan<byte> s, IFormatProvider provider, out SecureChar result)
		{
			if (char.TryParse(System.Text.Encoding.UTF8.GetString(s), out char plain))
			{
				result = new SecureChar(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Tries to format the decrypted value as UTF-8 bytes.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			((System.IUtf8SpanFormattable)Decrypted).TryFormat(utf8Destination, out bytesWritten, format, provider);
#endif
	}
}
