// <auto-generated>
// This file was generated by SecureValue.CodeGen. Do not edit by hand;
// edit the generator and re-run: dotnet run --project SecureValue.CodeGen
// </auto-generated>
using System;
using System.Runtime.CompilerServices;

namespace SecureValue
{
#if NET6_0_OR_GREATER
	public partial struct SecureTimeOnly : IComparable, IComparable<SecureTimeOnly>, IComparable<TimeOnly>, IEquatable<SecureTimeOnly>, IEquatable<TimeOnly>, IFormattable, ISecureValue<TimeOnly>
#if NET6_0_OR_GREATER
			,
			ISpanFormattable
#endif
#if NET7_0_OR_GREATER
			,
			IParsable<SecureTimeOnly>,
			ISpanParsable<SecureTimeOnly>
#endif
#if NET8_0_OR_GREATER
			,
			IUtf8SpanFormattable
#endif
	{
		/// <summary>Tests a secured TimeOnly value and a TimeOnly value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(SecureTimeOnly a, TimeOnly b) =>
			a.Decrypted == b;

		/// <summary>Tests a TimeOnly value and a secured TimeOnly value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator ==(TimeOnly a, SecureTimeOnly b) =>
			a == b.Decrypted;

		/// <summary>Tests a secured TimeOnly value and a TimeOnly value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(SecureTimeOnly a, TimeOnly b) =>
			a.Decrypted != b;

		/// <summary>Tests a TimeOnly value and a secured TimeOnly value for inequality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator !=(TimeOnly a, SecureTimeOnly b) =>
			a != b.Decrypted;

		/// <summary>Compares a secured TimeOnly value and a TimeOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(SecureTimeOnly a, TimeOnly b) =>
			a.Decrypted < b;

		/// <summary>Compares a TimeOnly value and a secured TimeOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <(TimeOnly a, SecureTimeOnly b) =>
			a < b.Decrypted;

		/// <summary>Compares a secured TimeOnly value and a TimeOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(SecureTimeOnly a, TimeOnly b) =>
			a.Decrypted <= b;

		/// <summary>Compares a TimeOnly value and a secured TimeOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator <=(TimeOnly a, SecureTimeOnly b) =>
			a <= b.Decrypted;

		/// <summary>Compares a secured TimeOnly value and a TimeOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(SecureTimeOnly a, TimeOnly b) =>
			a.Decrypted > b;

		/// <summary>Compares a TimeOnly value and a secured TimeOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >(TimeOnly a, SecureTimeOnly b) =>
			a > b.Decrypted;

		/// <summary>Compares a secured TimeOnly value and a TimeOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(SecureTimeOnly a, TimeOnly b) =>
			a.Decrypted >= b;

		/// <summary>Compares a TimeOnly value and a secured TimeOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static bool operator >=(TimeOnly a, SecureTimeOnly b) =>
			a >= b.Decrypted;

		/// <summary>Compares the decrypted value with a plain TimeOnly value for equality.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		bool IEquatable<TimeOnly>.Equals(TimeOnly other) =>
			Decrypted.Equals(other);

		/// <summary>Compares the decrypted value with a plain TimeOnly value.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		int IComparable<TimeOnly>.CompareTo(TimeOnly other) =>
			Decrypted.CompareTo(other);
#if NET6_0_OR_GREATER
		/// <summary>Tries to format the decrypted value into the destination span.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			Decrypted.TryFormat(destination, out charsWritten, format, provider);
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureTimeOnly parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureTimeOnly System.IParsable<SecureTimeOnly>.Parse(string s, IFormatProvider provider) =>
			new SecureTimeOnly(TimeOnly.Parse(s, provider));

		/// <summary>Tries to parse input into its secured form (explicit SecureTimeOnly parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.IParsable<SecureTimeOnly>.TryParse(string s, IFormatProvider provider, out SecureTimeOnly result)
		{
			if (TimeOnly.TryParse(s, provider, System.Globalization.DateTimeStyles.None, out TimeOnly plain))
			{
				result = new SecureTimeOnly(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET7_0_OR_GREATER
		/// <summary>Parses input into its secured form (explicit SecureTimeOnly parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static SecureTimeOnly System.ISpanParsable<SecureTimeOnly>.Parse(ReadOnlySpan<char> s, IFormatProvider provider)
		{
			if (TimeOnly.TryParse(s, provider, System.Globalization.DateTimeStyles.None, out TimeOnly plain))
			{
				return new SecureTimeOnly(plain);
			}

			throw new System.FormatException("Input was not in a correct format.");
		}

		/// <summary>Tries to parse input into its secured form (explicit SecureTimeOnly parsing).</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		static bool System.ISpanParsable<SecureTimeOnly>.TryParse(ReadOnlySpan<char> s, IFormatProvider provider, out SecureTimeOnly result)
		{
			if (TimeOnly.TryParse(s, provider, System.Globalization.DateTimeStyles.None, out TimeOnly plain))
			{
				result = new SecureTimeOnly(plain);
				return true;
			}

			result = default;
			return false;
		}
#endif
#if NET8_0_OR_GREATER
		/// <summary>Tries to format the decrypted value as UTF-8 bytes.</summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider provider) =>
			((System.IUtf8SpanFormattable)Decrypted).TryFormat(utf8Destination, out bytesWritten, format, provider);
#endif
	}
#endif
}
